# Generated by Django 5.2.14 on 2026-05-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_booking_link_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='plan',
            field=models.CharField(choices=[('link', 'Booking link\n£50/mo · one shareable URL'), ('widget', 'Embedded widget\n£60/mo · books on your website')], default='link', max_length=20),
        ),
    ]
